### ISSUE TITLE
Poetry 2.0 support

### ISSUE THREAD

**Issue by pietrodn** [snyk/snyk-poetry-lockfile-parser#27]
`snyk test` crashes if the `pyproject.toml` is in the [Poetry 2.0](https://github.com/python-poetry/poetry/blob/main/CHANGELOG.md#200---2025-01-05) format.

Simple repro case:

`pyproject.toml`:

```toml
[project]
name = "snyk2"
version = "0.1.0"
description = ""
authors = [
    {name = "Pietro De Nicolao",email = "pd@bendingspoons.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

`poetry.lock`:

```
# This file is automatically @generated by Poetry 2.0.0 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.1"
python-versions = ">=3.12"
content-hash = "75265641fd1a3f2a4d608312a3879427b7141ac2a51d0873da5711cbc8ead28e"
```

Command that fails:
```sh
$ snyk test --dev --prune-repeated-subdependencies
Error processing poetry project. Unable to parse manifest file
```
